{% set name = "urllib3-future" %}
{% set version = "2.10.905" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/urllib3_future-{{ version }}.tar.gz
  sha256: b4955f1ccea20f76a762cec2d1800148256f9fe5fe057987f90de733c3afe48d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.6.0,<2
    - pip
  run:
    - python >=3.8
    - qh3 >=1.0.3,<2.0.0
    - h11 >=0.11.0,<1.0.0
    - jh2 >=5.0.3,<6.0.0

test:
  imports:
    - urllib3_future
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jawah/urllib3.future
  summary: urllib3.future is a powerful HTTP 1.1, 2, and 3 client with both sync and async interfaces
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
