{% set name = "urllib3-future" %}
{% set version = "2.13.904" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/urllib3_future-{{ version }}.tar.gz
  sha256: 0b74239e4a663683fda362a47176ff00e3efb81b4031e721e0da06f358155c7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.6.0,<2
    - pip
  run:
    - python >={{ python_min }}
    - qh3 >=1.5.4,<2.0.0
    - h11 >=0.11.0,<1.0.0
    - jh2 >=5.0.3,<6.0.0

test:
  imports:
    - urllib3_future
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jawah/urllib3.future
  summary: urllib3.future is a powerful HTTP 1.1, 2, and 3 client with both sync and async interfaces
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
    - jan-janssen
